import { describe, it, expect } from "vitest";
import { validateStudy, validateAnalysis, validateGeneration, countWords, parseModelJson } from "../../utils/dscValidation.js";
import { analysisPrompt, generationPrompt } from "../../utils/dscMethodology.js";

export const input = () => ({ titulo: "Acesso à saúde", pergunta: "Como você avalia o acesso?", categorias: [{ nome: "Custo" }, { nome: "Transporte" }], respondentes: [{ nome: "Ana", sexo: "Feminino", depoimento: "Não consigo pagar. O ônibus demora." }, { nome: "Bia", depoimento: "Não tenho dinheiro." }] });
export const extracted = () => ({ respondentes: [{ id: "r1", palavrasChave: ["custo", "ônibus"], unidades: [{ expressao: "Não consigo pagar.", ideiaCentral: "Dificuldade financeira", categoriaId: "c1", ancoragem: null }, { expressao: "O ônibus demora.", ideiaCentral: "Demora do transporte", categoriaId: "c2", ancoragem: null }] }, { id: "r2", palavrasChave: ["dinheiro"], unidades: [{ expressao: "Não tenho dinheiro.", ideiaCentral: "Dificuldade financeira", categoriaId: "c1", ancoragem: null }] }] });

describe("Validação do fluxo DSC", () => {
  it.each([{}, { ...input(), categorias: [] }, { ...input(), respondentes: [] }, { ...input(), respondentes: [{ nome: "Ana" }] }, { ...input(), categorias: [null] }, { ...input(), categorias: [{ nome: "A" }, { nome: " a " }] }])("bloqueia entrada incompleta ou inválida", value => { expect(() => validateStudy(value)).toThrow(); });
  it("preserva campos não informados sem inventar demografia", () => { const d = validateStudy(input()); expect(d.respondentes[1].renda).toBe(""); expect(d.respondentes[0].id).toBe("r1"); });
  it("aceita vários sentidos de uma pessoa em categorias diferentes", () => { const a = validateAnalysis(extracted(), validateStudy(input())); expect(a.respondentes[0].unidades.map(u => u.categoriaId)).toEqual(["c1", "c2"]); });
  it("rejeita expressões-chave fabricadas ou com negação apagada da citação", () => { const a = extracted(); a.respondentes[0].unidades[0].expressao = "Consigo pagar tranquilamente."; expect(() => validateAnalysis(a, validateStudy(input()))).toThrow(/literal/); });
  it("exige fonte literal para a ancoragem", () => { const a = extracted(); a.respondentes[0].unidades[0].ancoragem = { expressao: "Saúde é um direito.", descricao: "Direito universal" }; expect(() => validateAnalysis(a, validateStudy(input()))).toThrow(/ancoragem/); });
  it("não aceita categoria inexistente ou respondente omitido", () => { const a = extracted(); a.respondentes[0].unidades[0].categoriaId = "c99"; expect(() => validateAnalysis(a, validateStudy(input()))).toThrow(/Categoria/); a.respondentes.pop(); expect(() => validateAnalysis(a, validateStudy(input()))).toThrow(/todos/); });
  it("aceita unidade sem categoria para revisão humana", () => { const a = extracted(); a.respondentes[0].unidades[0].categoriaId = null; expect(validateAnalysis(a, validateStudy(input())).respondentes[0].unidades[0].categoriaId).toBeNull(); });
  it("conta palavras com acentos e pontuação e aceita exatamente dez", () => { expect(countWords("Não consigo pagar o transporte para chegar à minha consulta.")).toBe(10); expect(countWords("Sinto-me bem; porém, não consigo pagar.")).toBe(6); });
  it("rejeita DSC de onze palavras e frases múltiplas", () => {
    const data = validateStudy(input()), a = validateAnalysis(extracted(), data);
    for (const texto of ["Não consigo pagar o transporte para chegar à minha consulta hoje.", "Não consigo pagar. Preciso de ajuda."]) expect(() => validateGeneration({ discursos: [{ categoriaId: "c1", texto }, { categoriaId: "c2", texto: "Espero pelo ônibus." }] }, data, a)).toThrow();
  });
  it("exige um resultado por categoria e constrói fontes sem confiar nos IDs da IA", () => { const data = validateStudy(input()), a = validateAnalysis(extracted(), data); const out = validateGeneration({ discursos: [{ categoriaId: "c1", texto: "Não consigo pagar.", fontes: ["inventado"] }, { categoriaId: "c2", texto: "Espero pelo ônibus." }] }, data, a); expect(out[0].fontes).toEqual([{ respondenteId: "r1", unidadeId: "r1u1" }, { respondenteId: "r2", unidadeId: "r2u1" }]); expect(() => validateGeneration({ discursos: [] }, data, a)).toThrow(); });
  it("categoria sem fonte fica pendente, mesmo se a IA inventar um texto", () => { const data = validateStudy(input()), a = validateAnalysis(extracted(), data); a.respondentes[0].unidades[1].categoriaId = null; const out = validateGeneration({ discursos: [{ categoriaId: "c1", texto: "Não consigo pagar." }, { categoriaId: "c2", texto: "Adoro andar de ônibus." }] }, data, a); expect(out[1].texto).toBeNull(); expect(out[1].fontes).toEqual([]); });
  it("preserva pendência em vez de forçar consenso", () => { const data = validateStudy(input()), a = validateAnalysis(extracted(), data); const out = validateGeneration({ discursos: [{ categoriaId: "c1", texto: null, pendencia: "Reveja os sentidos incompatíveis." }, { categoriaId: "c2", texto: "Espero pelo ônibus." }] }, data, a); expect(out[0].pendencia).toMatch(/incompatíveis/); });
  it("recusa JSON quebrado e aceita cerca markdown do provedor", () => { expect(() => parseModelJson("não é JSON")).toThrow(); expect(parseModelJson('```json\n{"respondentes":[]}\n```')).toEqual({ respondentes: [] }); });
  it("envia apenas identificadores e depoimentos para análise, sem nomes ou demografia", () => { const data = validateStudy(input()); const prompt = analysisPrompt(data); const sent = JSON.parse(prompt.split("DADOS_JSON:\n")[1]); expect(sent.respondentes[0]).toEqual({ id: "r1", depoimento: data.respondentes[0].depoimento }); expect(generationPrompt(data, validateAnalysis(extracted(), data), "Mais direto")).toContain("NO MÁXIMO 10 palavras"); });
});
